### ISSUE TITLE
Todo App 요구사항 명세서

### ISSUE THREAD

**Issue by JHJFE** [JHJFE/setting_practice#1]
## Todo Update Function

- [ ]  Search the specific data to update

- [ ] Get the data that will be updated

- [ ] Change the data and restore
## Estimated working hours 
- 3-4 hours
